{application,phoenixchannelclient,
             [{applications,[kernel,stdlib,elixir,logger,socket,poison,flow]},
              {description,"Phoenix Channel Client"},
              {modules,['Elixir.PhoenixChannelClient',
                        'Elixir.PhoenixChannelClient.Channel',
                        'Elixir.PhoenixChannelClient.Socket',
                        'Elixir.PhoenixChannelClient.Subscription']},
              {registered,[]},
              {vsn,"0.1.3"},
              {extra_applications,[logger]}]}.
